In [4]:
import numpy as np

print(np.__version__)

# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4])
print("1D Array:", array_1d)  # Expected Output: 1D Array: [1 2 3 4]

# Creating a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)
# Expected Output:
# 2D Array:
# [[1 2 3]
#  [4 5 6]]

# Array attributes
print("Shape:", array_2d.shape)  # Expected Output: Shape: (2, 3) - 2 rows and 3 columns
print("Size:", array_2d.size)   # Expected Output: Size: 6 - Total 6 elements
print("Data Type:", array_2d.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)

2.3.0
1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data Type: int64


1. Create Arrays: Create a 1D array with numbers from 1 to 5 and a 2D array with numbers from 1 to 6 (reshape it to have 2 rows and 3 columns).

USE:(https://numpy.org/doc/stable/reference/generated/numpy.reshape.html), (https://numpy.org/doc/stable/reference/generated/numpy.arange.html)

2. Inspect Attributes: For each array you created, print its shape, size, and data type.

3. Play with Data Types: Create a new array with numbers from 1 to 3, but specify the data type as float. Check and print its data type.

Expected Output:

Prints of the created arrays with their respective shapes, sizes, and data types.
An array with a specified data type different from the default.

In [13]:
#1. Create Arrays: Create a 1D array with numbers from 1 to 5 and a 2D array with numbers from 1 to 6 (reshape it to have 2 rows and 3 columns).
array1D = np.arange(start=1, stop=6)
print(array_1d)
array2D= np.arange(start=1, stop=7).reshape(2,3)
print(array2D)

#2. Inspect Attributes: For each array you created, print its shape, size, and data type.
print(array1D.shape, array1D.size, array1D.dtype)
print(array2D.shape, array2D.size, array2D.dtype)

#3. Play with Data Types: Create a new array with numbers from 1 to 3, but specify the data type as float. Check and print its data type.
array1D_float = np.arange(start=1, stop=4, dtype='float')
print(array1D_float.dtype)




[1 2 3 4]
[[1 2 3]
 [4 5 6]]
(5,) 5 int64
(2, 3) 6 int64
float64


A one dimensional array with the temperatures from this week.
A two dimensional array of shape 2,5 with random values (choose them yourself) from 1 to 10.
A 3D array with valid pixel values for a picture with 9 pixels.

In [19]:
#A one dimensional array with the temperatures from this week.
temperatures = np.array([25, 27, 30, 28, 24, 27, 29])

#A two dimensional array of shape 2,5 with random values (choose them yourself) from 1 to 10.
import random
random_2D = np.array([random.randint(1, 10) for _ in range(10)]).reshape(2, 5)

#A 3D array with valid pixel values for a picture with 9 pixels.
pixel_3D = np.array([random.randint(0, 255) for _ in range(27)]).reshape(3, 3, 3)
print(pixel_3D)

[[[126  96  65]
  [202 199   3]
  [ 39 178 128]]

 [[ 91   7 252]
  [ 78 120 128]
  [223 142 206]]

 [[157 216  49]
  [223 143 112]
  [ 90  18 135]]]


1. Basic Indexing: Create an array of 10 elements and access the 5th element in it.

2. Basic Slicing: From the same array, extract a slice containing the 3rd to the 8th elements.

3. Boolean Indexing: Create an array of 6 random integers between 10 and 50. Print the elements that are greater than 30.

4. Fancy Indexing: From the same array, use fancy indexing to access the 2nd, 4th, and 6th elements.

Expected Output:

The 5th element of the first array.
A slice of the array showing elements from the 3rd to the 8th position.
Elements greater than 30 from the random array.
Selected elements (2nd, 4th, 6th) from the random array using fancy indexing.

In [38]:
#1. Basic Indexing: Create an array of 10 elements and access the 5th element in it.
array_basic_indexing = np.arange(start=0, stop=10)
print(array_basic_indexing)
print(array_basic_indexing[4])

#2. Basic Slicing: From the same array, extract a slice containing the 3rd to the 8th elements.
print(array_basic_indexing[2:8])

#3. Boolean Indexing: Create an array of 6 random integers between 10 and 50. Print the elements that are greater than 30.
random_bool_indexing = np.random.randint(10, 50, 6)
print(random_bool_indexing)
print(random_bool_indexing[random_bool_indexing > 30])

#4. Fancy Indexing: From the same array, use fancy indexing to access the 2nd, 4th, and 6th elements.
print(random_bool_indexing[1::2])



[0 1 2 3 4 5 6 7 8 9]
4
[2 3 4 5 6 7]
[40 22 36 49 44 46]
[40 36 49 44 46]
[22 49 46]


After learning about array indexing and slicing, it's important to practice these concepts. Here are some exercises to help solidify your understanding:

1. Modifying Specific Elements:

Create an array with values from 1 to 10. Change the value of the fifth element to 50.

2. Slicing and Modifying a Range:

Given an array of 10 elements, modify the elements from index 3 to 7 to be their negative equivalent.

3. Conditional Modification with Boolean Indexing:

Create an array with 20 random integers between 1 and 100. Set all values greater than 50 to -1.

4. Advanced Indexing Modification:

Given a 2D array of shape (5, 5), modify the elements in the diagonal to be twice their original value.

5. Understanding Slicing Impact:

Create an array of 10 elements. Slice the array from index 2 to 5, and modify the first element of the slice. Observe the change in the original array.

In [48]:
#Create an array with values from 1 to 10. Change the value of the fifth element to 50.
array = np.arange(1, 11)
print(array)
array[4] = 50
print(array)
#Given an array of 10 elements, modify the elements from index 3 to 7 to be their negative equivalent.
array[3:7] = -array[3:7]
print(array)
#Create an array with 20 random integers between 1 and 100. Set all values greater than 50 to -1.
array2 = np.random.randint(1, 100, 20)
print(array2)
array2[array2 > 50] = -1
print(array2)
#Given a 2D array of shape (5, 5), modify the elements in the diagonal to be twice their original value.
array_2D_2 = np.arange(1, 26).reshape(5,5)
print(array_2D_2)
np.fill_diagonal(array_2D_2, 2 * array_2D_2.diagonal())
print(array_2D_2)
#Create an array of 10 elements. Slice the array from index 2 to 5, and modify the first element of the slice. Observe the change in the original array.
array_slice = array[2:5]
print(array_slice)
array_slice[0] = 26
print(array_slice)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4 50  6  7  8  9 10]
[  1   2   3  -4 -50  -6  -7   8   9  10]
[45 40 98 98  5 70 84 50 25 65 27 78  5 66  4 72 42 46 20 13]
[45 40 -1 -1  5 -1 -1 50 25 -1 27 -1  5 -1  4 -1 42 46 20 13]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 2  2  3  4  5]
 [ 6 14  8  9 10]
 [11 12 26 14 15]
 [16 17 18 38 20]
 [21 22 23 24 50]]
[  3  -4 -50]
[ 26  -4 -50]
[  1   2  26  -4 -50  -6  -7   8   9  10]


1. Arithmetic Operations: Create two 1D arrays of 3 elements each and perform element-wise addition, subtraction, multiplication, and division.

2. Aggregation Functions: For the arrays created above, find the sum, mean, minimum, and maximum of each array.

3. Broadcasting with Scalar: Multiply one of the arrays by a scalar (e.g., 5) and observe the result.

In [52]:
#1. Arithmetic Operations: Create two 1D arrays of 3 elements each and perform element-wise addition, subtraction, multiplication, and division.
array_1D_ari_op_1 = np.random.randint(1, 50, 3)
array_1D_ari_op_2 = np.random.randint(1, 50, 3)
print(array_1D_ari_op_1)
print(array_1D_ari_op_2)
addition = array_1D_ari_op_1 + array_1D_ari_op_2
print(addition)
substraction = array_1D_ari_op_1 - array_1D_ari_op_2
print(substraction)
multplication = array_1D_ari_op_1 * array_1D_ari_op_2
print(multplication)
division = array_1D_ari_op_1 / array_1D_ari_op_2
print(division)

#2. Aggregation Functions: For the arrays created above, find the sum, mean, minimum, and maximum of each array.
print(np.sum(array_1D_ari_op_1), np.mean(array_1D_ari_op_1), np.min(array_1D_ari_op_1), np.max(array_1D_ari_op_1))
print(np.sum(array_1D_ari_op_2), np.mean(array_1D_ari_op_2), np.min(array_1D_ari_op_2), np.max(array_1D_ari_op_2))

#3. Broadcasting with Scalar: Multiply one of the arrays by a scalar (e.g., 5) and observe the result.
broadcast = array_1D_ari_op_1 * 5
print(broadcast)

[ 5 25 37]
[ 1 22 15]
[ 6 47 52]
[ 4  3 22]
[  5 550 555]
[5.         1.13636364 2.46666667]
67 22.333333333333332 5 37
38 12.666666666666666 1 22
[ 25 125 185]


1. Reshape Array: Create a 1D array with 12 elements and reshape it to a 4x3 matrix. Then reshape it to a 2x6 matrix.

2. Transpose Matrix: Transpose the 2x6 matrix you created in the previous step.

3. Combine Reshaping and Transposing: Create a 3x4 matrix, transpose it, and then reshape the transposed matrix to a 1D array.

In [61]:
array_2_reshape = np.arange(12)
print(array_2_reshape)
array_reshaped = array_2_reshape.reshape(4, 3)
print(array_reshaped)

transposed = array_reshaped.T
print(transposed)

new_1D = transposed.reshape(1, -1)
new_1D_2 = transposed.reshape(1, 12)
print(new_1D)
print(new_1D_2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[ 0  3  6  9  1  4  7 10  2  5  8 11]]
[[ 0  3  6  9  1  4  7 10  2  5  8 11]]
