Exercise 1 : Array Creation And Manipulation

Instructions

Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output:
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import numpy as np

array_1D = np.arange(0, 10)
array_1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Exercise 2 : Type Conversion And Array Operations

Instructions

Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

Expected Output:



array([3, 2, 0, 1, 2])

In [3]:
list_to_convert = [3.14, 2.17, 0, 1, 2]
list_2_array = np.array(list_to_convert, dtype='int')
list_2_array

array([3, 2, 0, 1, 2])

Exercise 3 : Working With Multi-Dimensional Arrays

Instructions

Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
array_3x3 = np.arange(start= 1, stop= 10).reshape(3, 3)
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Exercise 4 : Creating Multi-Dimensional Array With Random Numbers

Instructions

Create a 2D NumPy array of shape (4, 5) filled with random numbers.

Expected Output:



array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])

In [16]:
array_4x5_random = np.around(np.random.rand(4, 5), 2)
array_4x5_random

array([[0.87, 0.54, 0.51, 0.54, 0.26],
       [0.29, 0.86, 0.79, 0.36, 0.88],
       [0.43, 0.15, 0.66, 0.12, 0.23],
       [0.98, 0.39, 0.19, 0.63, 0.62]])

Exercise 5 : Indexing Arrays

Instructions

Select the second row from a given 2D NumPy array.

Expected Output:



array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

In [8]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
array[1,:]


array([20, 21, 22, 23, 24])

Exercise 6 : Reversing Elements

Instructions

Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:



array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [12]:
array_1D[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Exercise 7 : Identity Matrix

Instructions

Create a 4x4 identity matrix using NumPy.

Expected Output:



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
identity_4x4 = np.around(np.identity(4, dtype='float'), 1)
identity_4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Exercise 8 : Simple Aggregate Funcs

Instructions

Find the sum and average of a given 1D array.

Expected Output:



Sum: 45, Average: 4.5

In [15]:
print(f"Sum: {array_1D.sum()}, Average:{array_1D.mean()}")

Sum: 45, Average:4.5


Exercise 9 : Create Array And Change Its Structure

Instructions

Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [17]:
array_4x5 = np.arange(1, 21).reshape(4, 5)
array_4x5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Exercise 10 : Conditional Selection Of Values

Instructions

Extract all odd numbers from a given NumPy array.

Expected Output:



array([1, 3, 5, 7, 9])

In [19]:
array_1D[array_1D%2 != 0]

array([1, 3, 5, 7, 9])